language: go

services:
  - docker

env:
  - IMAGE=go-pay-me

before_script:
  - cd implementation
  - docker build -t ${IMAGE}:test --target test --pull .
  - docker build -t ${IMAGE}:prod --target prod --pull .

script:
  - docker run --rm ${IMAGE}:test
