language: go

services:
  - docker

before_script:
  - env
  - cd implementation
  - docker build -t go-pay-me:test --target test --pull .
  - docker build -t go-pay-me:prod --target prod --pull .

script:
  - docker run --rm go-pay-me:test
