language: go

services:
  - docker

env:
  global:
    - IMAGE=go-pay-me
    - HEROKU_APP_NAME=go-pay-me
    - HEROKU_IMAGE=registry.heroku.com/go-pay-me/web

before_install:
  - wget -qO- https://toolbelt.heroku.com/install.sh | sh
  - echo ${HEROKU_PASSWORD} | docker login -u _ --password-stdin registry.heroku.com

before_script:
  - cd implementation

script:
  - docker-compose -f docker-compose.yml -f docker-compose.test.yml up --build --remove-orphans --exit-code-from go-pay-me-tests
  - docker build -t ${IMAGE}:prod --target prod --pull .
  - docker tag ${IMAGE}:prod ${HEROKU_IMAGE}

deploy:
  provider: script
  script: docker push ${HEROKU_IMAGE} && heroku container:release web --app ${HEROKU_APP_NAME}
  on:
    branch: master
