version: "3.4"
services:
  go-pay-me-tests:
    build:
      context: .
      target: test
    entrypoint: /bin/bash
    command: -c "./wait-for.sh postgres:5432 -t 10 -- ./wait-for.sh go-pay-me:8000 -t 10 -- make test-async && make test-sync"
    environment:
      - API_HOST=go-pay-me
      - API_PORT=8000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=payments
    links:
      - go-pay-me
      - postgres
    restart: "no"
