version: "3.4"
services:
  go-pay-me:
    build:
      context: .
      target: prod
    entrypoint: /bin/bash
    command: -c "/wait-for.sh postgres:5432 -t 10 -- /app"
    environment:
      - PORT=8000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=payments
    expose:
      - 8000
    links:
      - postgres

  postgres:
    image: postgres
    restart: always
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=payments
